//% color=#802626
//% block="Fire Sprites"
namespace fireEffect {
    /**
     * Creates a fire spawner that can used to spawn fire sprites. Fire spawners
     * manage the number of fire simulations running at once. If you are spawning
     * a lot of fire sprites, the spawner will reuse existing fire simulations instead
     * of creating new ones, which improves performance. The number of simultaneous
     * fire simulations is determined by the max sources parameter.
     *
     * All fire sprites from a spawner share the same dimensions, strength, color ramp, and
     * update/sputter intervals. If your game needs different types of fire, you should create
     * one fire spawner for each type (e.g. one for lanterns, one for campfires, one for attacks, etc.)
     *
     *
     * @param width The width of the sprites generated by this spawner.
     * @param height The height of sprites generated by this spawner. If this is too low, the fire may be cut off at higher strength values.
     * @param strength The strength of the fire. Higher numbers will result in a brighter, taller fire.
     * @param maxSources The max number of unique fire simulations.
     * @param roundedBottom If true, the fire will have a rounded bottom edge.
     * @returns A fire spawner that can be used to spawn fire sprites.
     */
    //% blockId=fireEffect_createFireSpawner
    //% block="create fire spawner with width $width height $height strength $strength||max sources $maxSources rounded bottom $roundedBottom"
    //% blockSetVariable=mySpawner
    //% width.defl=8
    //% height.defl=16
    //% strength.defl=30
    //% maxSources.defl=8
    //% inlineInputMode=inline
    //% help=github:arcade-fire-sprites/docs/create-fire-spawner
    //% weight=100
    export function createFireSpawner(
        width: number,
        height: number,
        strength: number,
        maxSources = 4,
        roundedBottom = false
    ): FireSpawner {
        width = Math.max(width, 1) | 0;
        height = Math.max(height, 1) | 0;
        strength = Math.max(strength, 0) | 0;
        maxSources |= 0;
        return new FireSpawner(
            width,
            height,
            strength,
            maxSources,
            roundedBottom
        );
    }

    /**
     * Creates a fire sprite from the given fire spawner with the specified sprite kind.
     *
     *
     * @param spawner The fire spawner to spawn the fire sprite from.
     * @param kind The SpriteKind of the spawned fire sprite.
     * @returns A Sprite
     */
    //% blockId=fireEffect_createFireSprite
    //% block="$spawner spawn sprite with kind $kind"
    //% blockSetVariable=myFireSprite
    //% spawner.shadow=variables_get
    //% spawner.defl=mySpawner
    //% kind.shadow=spritekind
    //% inlineInputMode=inline
    //% help=github:arcade-fire-sprites/docs/create-fire-sprite
    //% weight=90
    export function createFireSprite(
        spawner: FireSpawner,
        kind: number
    ): Sprite {
        return spawner.createSprite(kind);;
    }

    /**
     * Sets the strength of all fire sprites spawned from the given spawner. Higher strength
     * values will result in a taller, brighter flame.
     *
     * All sprites from the spawner share the same strength, so changing the strength will change
     * all existing sprites from that spawner.
     *
     *
     * @param spawner The spawner to set the strength of.
     * @param strength The strength of the fire. Higher numbers will result in a brighter, taller fire.
     */
    //% blockId=fireEffect_setSpawnerStrength
    //% block="$spawner set strength to $strength"
    //% spawner.shadow=variables_get
    //% spawner.defl=mySpawner
    //% strength.defl=30
    //% inlineInputMode=inline
    //% weight=80
    //% help=github:arcade-fire-sprites/docs/set-strength
    //% blockGap=8
    export function setStrength(
        spawner: FireSpawner,
        strength: number
    ) {
        spawner.setStrength(strength);
    }

    /**
     * Sets the update interval of the given fire spawner. The update interval controls how often
     * the fire simulation updates, in frames. A value of 1 wil update the fire every frame, a value of
     * 2 will update every other frame, etc. Higher values will slow down the fire animation.
     *
     * All sprites from the spawner share the same update interval, so changing the update interval will change
     * the animation speed of all existing sprites from that spawner.
     *
     *
     * @param spawner The spawner to set the update interval of.
     * @param interval The number of frames between fire updates. Higher values will slow down the fire animation.
     */
    //% blockId=fireEffect_setUpdateInterval
    //% block="$spawner set update interval to $interval"
    //% spawner.shadow=variables_get
    //% spawner.defl=mySpawner
    //% interval.defl=1
    //% interval.min=1
    //% inlineInputMode=inline
    //% weight=70
    //% blockGap=8
    //% help=github:arcade-fire-sprites/docs/set-update-interval
    export function setUpdateInterval(spawner: FireSpawner, interval: number) {
        spawner.updateInterval = Math.max(interval, 1) | 0;
    }

    /**
     * Sets the sputter interval of the given fire spawner. The sputter interval controls how often the fire will
     * sputter, which is when the fire randomly decreases in strength for a few frame to create a more natural flickering
     * effect. Higher values will result in less frequent sputterning.
     *
     * All sprites from the spawner share the same sputter interval, so changing the sputter interval will change
     * the sputtering frequency of all existing sprites from that spawner.
     *
     *
     * @param spawner The spawner to set the sputter interval of.
     * @param interval The number of frames between sputter events. Higher values will result in less frequent sputterning.
     */
    //% blockId=fireEffect_setSputterInterval
    //% block="$spawner set sputter interval $interval"
    //% spawner.shadow=variables_get
    //% spawner.defl=mySpawner
    //% interval.defl=30
    //% interval.min=3
    //% inlineInputMode=inline
    //% weight=60
    //% blockGap=8
    //% help=github:arcade-fire-sprites/docs/set-sputter-interval
    export function setSputterInterval(spawner: FireSpawner, interval: number) {
        spawner.sputterInterval = Math.max(interval, 3) | 0;
    }

    /**
     * Sets the color ramp used when drawing fires spawned by this fire spawner. The color ramp is a 6 pixel wide, 1 pixel
     * tall image that defines the colors used to draw the fire. The colors go from darkest to brightest as you move left to right. In general,
     * the first pixel of the ramp should always be transparent in order for the fire sprites to have a transparent background.
     *
     * All sprites from the spawner share the same color ramp, so changing the color ramp will change the colors of all existing sprites from that spawner.
     *
     *
     * @param spawner The spawner to set the color ramp of.
     * @param ramp The color ramp to use. Must be 6 pixels wide and 1 pixel tall.
     */
    //% blockId=fireEffect_setColorRamp
    //% block="$spawner set color ramp $ramp"
    //% spawner.shadow=variables_get
    //% spawner.defl=mySpawner
    //% ramp.shadow=fireEffect__image
    //% ramp.defl="img`. 2 4 5 1 1`"
    //% weight=0
    //% help=github:arcade-fire-sprites/docs/set-color-ramp
    export function setColorRamp(
        spawner: FireSpawner,
        ramp: Image
    ) {
        spawner.setRamp(ramp);
    }

    //% blockId=fireEffect__image block="%img"
    //% shim=TD_ID
    //% img.fieldEditor="sprite"
    //% img.fieldOptions.taggedTemplate="img"
    //% img.fieldOptions.decompileIndirectFixedInstances="true"
    //% img.fieldOptions.decompileArgumentAsString="true"
    //% img.fieldOptions.filter="!tile !dialog !background"
    //% img.fieldOptions.disableResize=1
    //% img.fieldOptions.initWidth=6
    //% img.fieldOptions.initHeight=1
    //% duplicateShadowOnDrag
    //% blockHidden=1
    export function _image(img: Image) {
        return img
    }
}